---
title: "Tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Function Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
--- 
```

library(readr)
library(googlesheets4)
gs4_deauth()
download.file("https://github.com/BennyShoe/Project_three/raw/refs/heads/main/data/R_Project1_Our_Data.csv","/cloud/project/data/Fish_Data.csv")

Make sure to put the data into a dataframe 

library(devtools)
devtools::install_github("BennyShoe/Project_three")
library(SchusterRPackage)


```

## Tutorial for each function

### Function One 

Filters the data to remove NAs and juveniles from the dataset.
```
Fish_Data <- read.csv("../data/Fish_Data.csv")

SchusterRPackage::Filter_Function(Fish_Data)
```
### Function Two 

Creates a violin plot that will be faceted by a designated variable. For testing I recommend using the example below.  
```

Fish_Data <- read.csv("../data/Fish_Data.csv")

library(ggplot2)
SchusterRPackage::Violin_Plot_Function(Fish_Data, SL, LL, Sex, "Sex", "SL", "LL")

```

### Function Three 

Allows you to check to see if fish in selected column are too small. I recommend using this function to look at standard lengths(SL) with a range of 15-30. 
```
Fish_Data <- read.csv("../data/Fish_Data.csv")
library(dplyr)
SchusterRPackage::my_function(Fish_Data, SL, 25)

```

### Function Four 

Calculates three ratios of a selected columns and adds a new columns the dataset with those values. The ratios are as followed SL_LL_Ratio(standard length to lateral line length) , SL_TV_Ratio(standard length to total vertebrae count) , and LL_TV_Ratio(lateral line length to total vertebrae count) . For the function to work add the columns in the order listed below. 

```

Fish_Data <- read.csv("../data/Fish_Data.csv")
SchusterRPackage::Ratio_Function(Fish_Data, SL, LL, TV)

```

### Function Five 

Creates a linear model graph. For testing I recommend using the example below.  

```
Fish_Data <- read.csv("../data/Fish_Data.csv")
library(ggplot2)
SchusterRPackage::LM_Graph_Function(Fish_Data, "SL", "LL")

```

### Function Six 

Creates various linear model tests to see if your data is normally distributed. For testing I recommend using the example below.  

```
Fish_Data <- read.csv("../data/Fish_Data.csv")
library(ggplot2)
SchusterRPackage::LM_Function(Fish_Data, "SL", "LL")

```


